
title: 学以致用
author: echoyuanliang
email: echoyuanliang@gmail.com
description: ""
show_excerpts: true # set to true to show excerpts on the homepage
# baseurl: /texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

paginate: 15
paginate_path: "page/:num"
baseurl: ""

permalink: /posts/:title/


defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css, tags.css]
      scripts : [tags.js, script.js]


texture:
  title: 学以致用
  tagline: DevOps
  date_format: "%b %-d, %Y" #"%Y-%m-%d"
  style: black
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    github:  echoyuanliang
    email: echoyuanliang@gmail.com
github:
  username: echoyuanliang
gitalk:
    repo: echoyuanliang.github.io
    client_id: a68c80416dfcbddfb36e
    client_secret: e779c75fe7bfb643491cbd8958f9060ff78a94bf


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
#  - jekyll-feed
